#/etc/X11/xorg.conf.d/10-monitor.conf
Section "Monitor"
        Identifier "eDP-1"
        Option "PreferredMode" "2560x1600"
EndSection

Section "screen"
        Identifier "Screen0"
        Monitor "eDP-1"
        DefaultDepth 24
        SubSection "Display"
                Modes "2560x1600"
        EndSubSection
EndSection
